<?php

declare(strict_types=1);

namespace App\Console\Commands\Api;

use App\Services\Api\OpenApiSpec;
use Illuminate\Console\Command;

class GenerateOpenApiSpec extends Command
{
    protected $signature = 'api:openapi
                            {--path= : Override the output path for the YAML document}
                            {--check : Exit non-zero when the document on disk is out of date}';

    protected $description = 'Regenerate the OpenAPI 3.1 document from the live route table';

    public function handle(OpenApiSpec $spec): int
    {
        $path = (string) ($this->option('path') ?: base_path('docs/api/openapi.yaml'));
        $yaml = $this->render($spec);

        if ($this->option('check')) {
            $current = is_file($path) ? (string) file_get_contents($path) : '';

            if ($current !== $yaml) {
                $this->error('Spec is stale. Run: php artisan api:openapi');

                return self::FAILURE;
            }

            $this->info('Spec is up to date ('.$spec->endpointCount().' operations).');

            return self::SUCCESS;
        }

        $directory = dirname($path);

        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        file_put_contents($path, $yaml);

        $this->info('Wrote '.$path);
        $this->line('  operations: '.$spec->endpointCount());
        $this->line('  bytes:     '.strlen($yaml));

        return self::SUCCESS;
    }

    private function render(OpenApiSpec $spec): string
    {
        $header = implode("\n", [
            '# Generated by `php artisan api:openapi` from the live route table.',
            '# Do not edit by hand: change routes/api.php or app/Services/Api/OpenApiSpec.php and regenerate.',
            '',
            '',
        ]);

        return $header.$spec->yaml()."\n";
    }
}
