@extends('layouts.admin')
@section('title', 'Detail Pelanggan')
@section('content')
<div class="mb-4"><a href="{{ route('admin.customers.index') }}" class="small"><i class="fas fa-arrow-left me-1"></i>Kembali</a><h4 class="fw-bold mt-2">{{ $customer->name }}</h4></div>
<div class="row g-4">
    <div class="col-lg-4"><div class="card border-0 rounded-4 shadow-sm"><div class="card-body text-center p-4"><div class="rounded-circle bg-primary bg-opacity-10 d-inline-flex align-items-center justify-content-center mb-3" style="width:72px;height:72px;"><i class="fas fa-user fa-2x text-primary"></i></div><h5 class="fw-bold">{{ $customer->name }}</h5><p class="text-muted small">{{ $customer->email }}<br>{{ $customer->phone ?? '-' }}</p><span class="badge bg-{{ $customer->status==='active'?'success' : 'secondary' }}-subtle px-3 py-2">{{ $customer->status }}</span><div class="mt-3 text-start"><small class="text-muted">Wallet</small><br><span class="fw-bold">Rp {{ number_format($customer->wallet->balance ?? 0, 0, ',', '.') }}</span></div><div class="mt-2 text-start"><small class="text-muted">Total Pesanan</small><br><span class="fw-bold">{{ $customer->orders_count }}</span></div></div></div></div>
    <div class="col-lg-8">
        @if($customer->addresses->count() > 0)<div class="card border-0 rounded-4 shadow-sm mb-3"><div class="card-header bg-transparent border-0 pt-3"><h6 class="fw-bold mb-0"><i class="fas fa-map-marker-alt me-2"></i>Alamat</h6></div><div class="card-body">@foreach($customer->addresses as $a)<div class="border-bottom pb-2 mb-2 small"><span class="fw-semibold">{{ $a->label }}</span> — {{ $a->receiver_name }} ({{ $a->receiver_phone }})<br><span class="text-muted">{{ $a->address }}, {{ $a->city }}, {{ $a->province }} {{ $a->postal_code }}</span></div>@endforeach</div></div>@endif
        <div class="card border-0 rounded-4 shadow-sm"><div class="card-header bg-transparent border-0 pt-3"><h6 class="fw-bold mb-0"><i class="fas fa-shopping-cart me-2"></i>Pesanan Terbaru</h6></div><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Order</th><th>Total</th><th>Status</th><th>Tgl</th></tr></thead><tbody>@forelse($customer->orders as $o)<tr><td class="fw-semibold small">{{ $o->order_number }}</td><td>Rp {{ number_format($o->total,0,',','.') }}</td><td><span class="badge bg-info-subtle text-info">{{ $o->order_status }}</span></td><td class="small">{{ $o->created_at->format('d/m/Y') }}</td></tr>@empty<tr><td colspan="4" class="text-center py-3 text-muted small">Belum ada pesanan</td></tr>@endforelse</tbody></table></div></div>
    </div>
</div>
@endsection
