@extends('layouts.admin')
@section('title', 'Detail Pelanggan')
@section('content')
<div class="mb-4"><a href="{{ route('admin.customers.index') }}" class="small"><x-admin.icon name="arrow-left" :size="16" class="me-1" />Kembali</a><h4 class="fw-bold mt-2">{{ $customer->name }}</h4></div>
<div class="row g-4">
    <div class="col-lg-4"><x-admin.card :padding="false"><div class="card-body text-center p-4"><div class="rounded-circle bg-primary bg-opacity-10 d-inline-flex align-items-center justify-content-center mb-3" style="width:72px;height:72px;"><x-admin.icon name="user" :size="32" class="text-primary" /></div><h5 class="fw-bold">{{ $customer->name }}</h5><p class="text-muted small">{{ $customer->email }}<br>{{ $customer->phone ?? '-' }}</p><x-admin.badge :color="$customer->status==='active'?'success' : 'secondary'" class="px-3 py-2" :text="$customer->status" /><div class="mt-3 text-start"><small class="text-muted">Wallet</small><br><span class="fw-bold">Rp {{ number_format($customer->wallet->balance ?? 0, 0, ',', '.') }}</span></div><div class="mt-2 text-start"><small class="text-muted">Total Pesanan</small><br><span class="fw-bold">{{ $customer->orders_count }}</span></div></div></x-admin.card></div>
    <div class="col-lg-8">
        @if($customer->addresses->count() > 0)<x-admin.card :padding="false" class="mb-3"><div class="card-header bg-transparent border-0 pt-3"><h6 class="fw-bold mb-0"><x-admin.icon name="map-pin" :size="16" class="me-2" />Alamat</h6></div><div class="card-body">@foreach($customer->addresses as $a)<div class="border-bottom pb-2 mb-2 small"><span class="fw-semibold">{{ $a->label }}</span> — {{ $a->receiver_name }} ({{ $a->receiver_phone }})<br><span class="text-muted">{{ $a->address }}, {{ $a->city }}, {{ $a->province }} {{ $a->postal_code }}</span></div>@endforeach</div></x-admin.card>@endif
        <x-admin.card :padding="false"><div class="card-header bg-transparent border-0 pt-3"><h6 class="fw-bold mb-0"><x-admin.icon name="shopping-cart" :size="16" class="me-2" />Pesanan Terbaru</h6></div><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Order</th><th>Total</th><th>Status</th><th>Tgl</th></tr></thead><tbody>@forelse($customer->orders as $o)<tr><td class="fw-semibold small">{{ $o->order_number }}</td><td>Rp {{ number_format($o->total,0,',','.') }}</td><td><x-admin.badge color="info" :text="$o->order_status" /></td><td class="small">{{ $o->created_at->format('d/m/Y') }}</td></tr>@empty<tr><td colspan="4" class="text-center py-3 text-muted small">Belum ada pesanan</td></tr>@endforelse</tbody></table></div></x-admin.card>
    </div>
</div>
@endsection
