@extends('layouts.admin')
@section('title', 'Withdraw Vendor')
@section('content')
<h4 class="fw-bold mb-1"><x-admin.icon name="cash" :size="20" class="me-2 text-success" /> Withdraw Vendor</h4>
<p class="text-muted small mb-3">Approve atau tolak permintaan pencairan dana vendor</p>
<x-admin.card :padding="false"><div class="p-3 border-bottom"><form method="GET" class="row g-2"><div class="col-md-2"><select name="status" class="form-select form-select-sm"><option value="">Semua</option><option value="pending" {{ request('status')==='pending'?'selected' : '' }}>Pending</option><option value="approved" {{ request('status')==='approved'?'selected' : '' }}>Approved</option><option value="completed" {{ request('status')==='completed'?'selected' : '' }}>Completed</option><option value="rejected" {{ request('status')==='rejected'?'selected' : '' }}>Rejected</option></select></div><div class="col-md-2"><button class="btn btn-outline-primary btn-sm w-100"><x-admin.icon name="filter" :size="14" class="me-1" />Filter</button></div></form></div>
<div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Vendor</th><th>Toko</th><th>Jumlah</th><th>Bank</th><th>Status</th><th>Tgl</th><th>Aksi</th></tr></thead><tbody>
@forelse($withdraws as $w)
<tr><td>{{ $w->vendor->name ?? '-' }}<br><small>{{ $w->vendor->email ?? '' }}</small></td><td>{{ $w->shop->name ?? '-' }}</td><td class="fw-bold">Rp {{ number_format($w->amount,0,',','.') }}</td><td><small>{{ $w->bank_name }}<br>{{ $w->bank_account_number }}<br>{{ $w->bank_account_name }}</small></td><td><x-admin.badge :color="['pending'=>'warning','approved'=>'info','completed'=>'success','rejected'=>'danger'][$w->status] ?? 'secondary'" :text="$w->status" /></td><td class="small">{{ $w->created_at->format('d/m/Y') }}</td>
<td>@if($w->status==='pending')<div class="d-flex gap-1"><form action="{{ route('admin.withdraws.update', $w) }}" method="POST" class="d-inline">@csrf @method('PUT')<input type="hidden" name="status" value="approved"><button class="btn btn-sm btn-success">Setuju</button></form><form action="{{ route('admin.withdraws.update', $w) }}" method="POST" class="d-inline">@csrf @method('PUT')<input type="hidden" name="status" value="rejected"><button class="btn btn-sm btn-danger">Tolak</button></form></div>@elseif($w->status==='approved')<form action="{{ route('admin.withdraws.update', $w) }}" method="POST">@csrf @method('PUT')<input type="hidden" name="status" value="completed"><button class="btn btn-sm btn-info">Selesai</button></form>@else - @endif</td></tr>
@empty<tr><td colspan="7" class="text-center py-5 text-muted">Belum ada withdraw</td></tr>@endforelse
</tbody></table></div>@if($withdraws->hasPages())<div class="p-3"><x-admin.pagination>{{ $withdraws->links() }}</x-admin.pagination></div>@endif</x-admin.card>
@endsection
